baseURL = "https://ashugoyal.in/"
languageCode = "en-us"
title = "Ashu Goyal"
theme = "PaperMod"

[params]
  author = "Ashu Goyal"
  defaultTheme = "auto"
  ShowReadingTime = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blogs"
    weight = 1

