baseURL = "https://ashugoyal.in/"
languageCode = "en-us"
title = "Ashu Goyal"
theme = "PaperMod"

[params]
  author = "Ashu Goyal"
  defaultTheme = "auto"
  ShowReadingTime = true
  mainSections = []

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blogs"
    weight = 1

  [[menu.main]]
    name = "Book a call"
    url = "https://calendly.com/ashugoyal6799/coffee-chat-your-tech-needs"
    weight = 2

