baseURL = "https://ashugoyal.in/"
languageCode = "en-us"
title = "Ashu Goyal"
theme = "PaperMod"

[params]
  author = "Ashu Goyal"
  defaultTheme = "auto"
  ShowReadingTime = true
  mainSections = []

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/ashu-goyal"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:ashugoyal6799@gmail.com"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blogs"
    weight = 1

  [[menu.main]]
    name = "Open Source"
    url = "/projects"
    weight = 2

  [[menu.main]]
    name = "Coffee Chat"
    url = "https://calendly.com/ashugoyal6799/coffee-chat-your-tech-needs"
    weight = 3

